// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import 'dart:core';
import 'package:extern_plugin_loader/reflectable_annotations.dart' as prefix0;
import 'package:extern_plugin_loader/src/base_plugin.dart' as prefix1;
import 'package:extern_plugin_loader/src/ingenico_plugin/ingenico_plugin.dart'
    as prefix2;
import 'package:extern_plugin_loader/src/tempus_plugin/tempus_plugin.dart'
    as prefix3;
import 'package:extern_plugin_loader/src/upi_plugin/upi_plugin.dart' as prefix4;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: unused_import

import 'package:reflectable/mirrors.dart' as m;
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.Reflector(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'BasePlugin',
            r'.BasePlugin',
            134218247,
            0,
            const prefix0.Reflector(),
            const <int>[3, 4, 5],
            const <int>[6, 7, 8, 9, 10],
            const <int>[],
            -1,
            {},
            {},
            {},
            -1,
            -1,
            const <int>[-1],
            const <Object>[prefix0.reflector],
            null),
        r.NonGenericClassMirrorImpl(
            r'IngenicoPlugin',
            r'.IngenicoPlugin',
            134217735,
            1,
            const prefix0.Reflector(),
            const <int>[0, 11, 12, 15],
            const <int>[6, 7, 8, 9, 10, 11, 12, 13, 14],
            const <int>[],
            -1,
            {},
            {},
            {r'': (bool b) => () => b ? prefix2.IngenicoPlugin() : null},
            -1,
            -1,
            const <int>[-1],
            const <Object>[prefix0.reflector],
            null),
        r.NonGenericClassMirrorImpl(
            r'TempusPlugin',
            r'.TempusPlugin',
            134217735,
            2,
            const prefix0.Reflector(),
            const <int>[1, 16, 17, 20],
            const <int>[6, 7, 8, 9, 10, 16, 17, 18, 19],
            const <int>[],
            -1,
            {},
            {},
            {r'': (bool b) => () => b ? prefix3.TempusPlugin() : null},
            -1,
            -1,
            const <int>[-1],
            const <Object>[prefix0.reflector],
            null),
        r.NonGenericClassMirrorImpl(
            r'UPIPlugin',
            r'.UPIPlugin',
            134217735,
            3,
            const prefix0.Reflector(),
            const <int>[2, 21, 22, 25],
            const <int>[6, 7, 8, 9, 10, 21, 22, 23, 24],
            const <int>[],
            -1,
            {},
            {},
            {r'': (bool b) => () => b ? prefix4.UPIPlugin() : null},
            -1,
            -1,
            const <int>[-1],
            const <Object>[prefix0.reflector],
            null)
      ],
      <m.DeclarationMirror>[
        r.VariableMirrorImpl(r'plugin', 134348805, 1, const prefix0.Reflector(),
            -1, -1, -1, null, const []),
        r.VariableMirrorImpl(r'plugin', 134348805, 2, const prefix0.Reflector(),
            -1, -1, -1, null, const []),
        r.VariableMirrorImpl(r'plugin', 134348805, 3, const prefix0.Reflector(),
            -1, -1, -1, null, const []),
        r.MethodMirrorImpl(r'getName', 2097666, 0, -1, -1, -1, null,
            const <int>[], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'performAction', 2097666, 0, -1, -1, -1, null,
            const <int>[], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'', 64, 0, -1, -1, -1, null, const <int>[],
            const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'==', 2097154, -1, -1, -1, -1, null, const <int>[0],
            const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'toString', 2097154, -1, -1, -1, -1, null,
            const <int>[], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'noSuchMethod', 524290, -1, -1, -1, -1, null,
            const <int>[1], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'hashCode', 2097155, -1, -1, -1, -1, null,
            const <int>[], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'runtimeType', 2097155, -1, -1, -1, -1, null,
            const <int>[], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'getName', 2097154, 1, -1, -1, -1, null,
            const <int>[], const prefix0.Reflector(), const <Object>[override]),
        r.MethodMirrorImpl(r'performAction', 2097154, 1, -1, -1, -1, null,
            const <int>[], const prefix0.Reflector(), const <Object>[override]),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 0, 13),
        r.ImplicitSetterMirrorImpl(const prefix0.Reflector(), 0, 14),
        r.MethodMirrorImpl(r'', 64, 1, -1, -1, -1, null, const <int>[],
            const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'getName', 2097154, 2, -1, -1, -1, null,
            const <int>[], const prefix0.Reflector(), const <Object>[override]),
        r.MethodMirrorImpl(r'performAction', 2097154, 2, -1, -1, -1, null,
            const <int>[], const prefix0.Reflector(), const <Object>[override]),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 1, 18),
        r.ImplicitSetterMirrorImpl(const prefix0.Reflector(), 1, 19),
        r.MethodMirrorImpl(r'', 64, 2, -1, -1, -1, null, const <int>[],
            const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'getName', 2097154, 3, -1, -1, -1, null,
            const <int>[], const prefix0.Reflector(), const <Object>[override]),
        r.MethodMirrorImpl(r'performAction', 2097154, 3, -1, -1, -1, null,
            const <int>[], const prefix0.Reflector(), const <Object>[override]),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 2, 23),
        r.ImplicitSetterMirrorImpl(const prefix0.Reflector(), 2, 24),
        r.MethodMirrorImpl(r'', 64, 3, -1, -1, -1, null, const <int>[],
            const prefix0.Reflector(), const [])
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(r'other', 134348806, 6, const prefix0.Reflector(),
            -1, -1, -1, null, const [], null, null),
        r.ParameterMirrorImpl(r'invocation', 134348806, 8,
            const prefix0.Reflector(), -1, -1, -1, null, const [], null, null),
        r.ParameterMirrorImpl(r'_plugin', 134348902, 14,
            const prefix0.Reflector(), -1, -1, -1, null, const [], null, null),
        r.ParameterMirrorImpl(r'_plugin', 134348902, 19,
            const prefix0.Reflector(), -1, -1, -1, null, const [], null, null),
        r.ParameterMirrorImpl(r'_plugin', 134348902, 24,
            const prefix0.Reflector(), -1, -1, -1, null, const [], null, null)
      ],
      <Type>[
        prefix1.BasePlugin,
        prefix2.IngenicoPlugin,
        prefix3.TempusPlugin,
        prefix4.UPIPlugin
      ],
      4,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'getName': (dynamic instance) => instance.getName,
        r'performAction': (dynamic instance) => instance.performAction,
        r'plugin': (dynamic instance) => instance.plugin
      },
      {r'plugin=': (dynamic instance, value) => instance.plugin = value},
      null,
      [])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
